version: '3'
services:
  test_db:
    restart: always
    image: postgres:11.7-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
